# Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM node:20.11.1
 
# A directory within the virtualized Docker environment
# Becomes more relevant when using Docker Compose later
WORKDIR /usr/src/app
 
# Uses port which is used by the actual application
EXPOSE 81
 
# Finally installs dependencies and runs the application
CMD npm install && node index.js

