version: '3.3'

services:

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./db:/var/lib/mysql

  strapi:
    container_name: strapi
    image: strapi/strapi:latest
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    command: sh -c "rm -rf node_modules package-lock.json && npm install"
    depends_on:
      - db

  backend:
    build:
      dockerfile: Dockerfile-backend
      context: ./backend
    container_name: backend
    expose:
    - 80
    - 81
    ports:
    - 80:80
    - 81:81
    volumes:
      - ./backend:/usr/src/app