services:

  backend:
    build:
      dockerfile: Dockerfile-backend
      context: ./backend
    container_name: backend
    expose:
    - 81
    ports:
    - 81:81
    volumes:
      - ./backend:/usr/src/app
